---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeMe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FinanceMe
  template:
    metadata:
      labels:
        app: FinanceMe
    spec:
      containers:
        - name: financeMe
          image: aakaash03/financeMe-august:latest
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: financeMe
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: financeMe
